name: Cancel
on:
  pull_request_target:
    types:
      - edited
      - synchronize

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          # See https://api.github.com/repos/toeverything/AFFiNE/actions/workflows
          workflow_id: 44038251, 61883931, 65188160, 66789140
          access_token: ${{ github.token }}
