name: PR Title Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - canary

permissions:
  contents: read

jobs:
  check-pull-request-title:
    name: Check pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          electron-install: false
      - run: echo "${{ github.event.pull_request.title }}" | yarn dlx commitlint -g ./.commitlintrc.json
